echo '| ----------------------------------------------------- |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                I am pre-build script                  |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '| ----------------------------------------------------- |'
