echo '| ----------------------------------------------------- |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '|         I am pre-build script for Flavor 1            |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '| ----------------------------------------------------- |'
