echo '| ----------------------------------------------------- |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '|         I am pre-build script for Flavor 2            |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '|                                                       |'
echo '| ----------------------------------------------------- |'

cp -r flavors/flavor_2/assets/ app/client_app/